### ISSUE TITLE
项目不能运行

### ISSUE THREAD

**Issue by kernnel** [steambap/vue-dates#1]
我按照文档来clone项目，npm install 报错，项目不能运行

**Comment by steambap** [comment]
报的啥错？

**Comment by kernnel** [comment]
我的环境是
macOs:10.13
npm版本：5.6.0，
下载zip，用npm install or cnpm install，安装就报错，缺少module

**Comment by kernnel** [comment]
而且看你的tag版本是0.2，但是下载下来的时候0.1

**Comment by steambap** [comment]
缺少module 是个啥错？
